
2021-02-02 02:38:16,143 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 02:39:18,602 ERROR: Exception on /artists/16/edit [GET] [in E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\VS code Projects\01_fyyur\starter_code\app.py", line 357, in edit_artist
    form = ArtistForm()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-02-02 02:40:26,567 ERROR: Exception on /venues/create [GET] [in E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\VS code Projects\01_fyyur\starter_code\app.py", line 163, in create_venue_form
    form = VenueForm()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\wtforms\form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\wtforms\form.py", line 131, in process
    field.process(formdata)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\wtforms\csrf\core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\csrf.py", line 139, in generate_csrf_token
    return generate_csrf(
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\csrf.py", line 33, in generate_csrf
    secret_key = _get_config(
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask_wtf\csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2021-02-02 02:43:54,112 INFO: errors [in app.py:661]
2021-02-02 02:49:44,779 ERROR: Exception on /artists/22 [GET] [in E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 301, in show_artist
    artist = artist_shows[0].artist
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\orm\query.py", line 3208, in __getitem__
    return list(self[item : item + 1])[0]
IndexError: list index out of range
2021-02-02 02:50:28,202 ERROR: Exception on /artists/22 [GET] [in E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 301, in show_artist
    artist = artist_shows[0].artist
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\orm\query.py", line 3208, in __getitem__
    return list(self[item : item + 1])[0]
IndexError: list index out of range
2021-02-02 02:54:32,294 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 02:59:48,083 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 03:00:14,467 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 03:00:34,582 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 03:01:42,889 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 03:01:58,177 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 03:02:32,178 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 03:02:51,984 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 03:05:56,153 INFO: errors [in E:\VS code Projects\01_fyyur\starter_code\app.py:661]
2021-02-02 03:09:47,140 INFO: errors [in app.py:661]
2021-02-02 03:12:13,082 ERROR: Exception on /venues/1 [GET] [in E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in show_venue
    venue = venue_shows[0].venue
  File "E:\VS code Projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\orm\query.py", line 3208, in __getitem__
    return list(self[item : item + 1])[0]
IndexError: list index out of range
2021-02-02 18:54:29,346 INFO: errors [in app.py:658]
